name=ARAM_FS_Stepper
version=1.0.1
author=A.R.A.M. - American Robotics Assisted Manufacturing
maintainer=A.R.A.M. - American Robotics Assisted Manufacturing <support@aram-usa.com>
sentence=Driver for A.R.A.M. Full Step Stepper Drivers
paragraph=This is a driver maintianed for all models of A.R.A.M. stepper motor driver modules, in production and design. Currently this applies to the ARAM-DDHBSD_0_10-0S. This library is made spefically to avoid high overhead, especially with ESP32 units. Please view the manual for information on usage.
category=Device Control
url=https://github.com/ARAM-USA-Support/ARAM_FS_Stepper
architectures=*s